# Form implementation generated from reading ui file 'catalogueWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_catalogueWindow(object):
    def setupUi(self, catalogueWindow):
        catalogueWindow.setObjectName("catalogueWindow")
        catalogueWindow.resize(800, 600)
        catalogueWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.tblCatFunctions = QtWidgets.QTableView(parent=catalogueWindow)
        self.tblCatFunctions.setGeometry(QtCore.QRect(39, 70, 721, 430))
        self.tblCatFunctions.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectItems)
        self.tblCatFunctions.setObjectName("tblCatFunctions")
        self.txtCatSearch = QtWidgets.QLineEdit(parent=catalogueWindow)
        self.txtCatSearch.setGeometry(QtCore.QRect(39, 40, 721, 30))
        self.txtCatSearch.setObjectName("txtCatSearch")
        self.btnCatGraph = QtWidgets.QPushButton(parent=catalogueWindow)
        self.btnCatGraph.setGeometry(QtCore.QRect(210, 530, 150, 35))
        self.btnCatGraph.setObjectName("btnCatGraph")
        self.btnCatHome = QtWidgets.QPushButton(parent=catalogueWindow)
        self.btnCatHome.setGeometry(QtCore.QRect(440, 530, 140, 35))
        self.btnCatHome.setObjectName("btnCatHome")

        self.retranslateUi(catalogueWindow)
        QtCore.QMetaObject.connectSlotsByName(catalogueWindow)

    def retranslateUi(self, catalogueWindow):
        _translate = QtCore.QCoreApplication.translate
        catalogueWindow.setWindowTitle(_translate("catalogueWindow", "Dialog"))
        self.txtCatSearch.setPlaceholderText(_translate("catalogueWindow", "Search"))
        self.btnCatGraph.setText(_translate("catalogueWindow", "Graph"))
        self.btnCatHome.setText(_translate("catalogueWindow", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    catalogueWindow = QtWidgets.QDialog()
    ui = Ui_catalogueWindow()
    ui.setupUi(catalogueWindow)
    catalogueWindow.show()
    sys.exit(app.exec())
