# Form implementation generated from reading ui file 'savedGraphsWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_savedGraphsWindow(object):
    def setupUi(self, savedGraphsWindow):
        savedGraphsWindow.setObjectName("savedGraphsWindow")
        savedGraphsWindow.resize(800, 600)
        savedGraphsWindow.setMinimumSize(QtCore.QSize(800, 600))
        savedGraphsWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.tblSvdGraphs = QtWidgets.QTableView(parent=savedGraphsWindow)
        self.tblSvdGraphs.setGeometry(QtCore.QRect(39, 70, 721, 430))
        self.tblSvdGraphs.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.tblSvdGraphs.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.tblSvdGraphs.setTabKeyNavigation(False)
        self.tblSvdGraphs.setAlternatingRowColors(False)
        self.tblSvdGraphs.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblSvdGraphs.setObjectName("tblSvdGraphs")
        self.tblSvdGraphs.horizontalHeader().setHighlightSections(False)
        self.txtCatSearch = QtWidgets.QLineEdit(parent=savedGraphsWindow)
        self.txtCatSearch.setGeometry(QtCore.QRect(39, 40, 721, 30))
        self.txtCatSearch.setObjectName("txtCatSearch")
        self.btnSvdLoad = QtWidgets.QPushButton(parent=savedGraphsWindow)
        self.btnSvdLoad.setGeometry(QtCore.QRect(210, 530, 150, 35))
        self.btnSvdLoad.setObjectName("btnSvdLoad")
        self.btnSvdHome = QtWidgets.QPushButton(parent=savedGraphsWindow)
        self.btnSvdHome.setGeometry(QtCore.QRect(440, 530, 140, 35))
        self.btnSvdHome.setObjectName("btnSvdHome")

        self.retranslateUi(savedGraphsWindow)
        QtCore.QMetaObject.connectSlotsByName(savedGraphsWindow)

    def retranslateUi(self, savedGraphsWindow):
        _translate = QtCore.QCoreApplication.translate
        savedGraphsWindow.setWindowTitle(_translate("savedGraphsWindow", "Dialog"))
        self.txtCatSearch.setPlaceholderText(_translate("savedGraphsWindow", "Search"))
        self.btnSvdLoad.setText(_translate("savedGraphsWindow", "Graph"))
        self.btnSvdHome.setText(_translate("savedGraphsWindow", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    savedGraphsWindow = QtWidgets.QDialog()
    ui = Ui_savedGraphsWindow()
    ui.setupUi(savedGraphsWindow)
    savedGraphsWindow.show()
    sys.exit(app.exec())
