# Form implementation generated from reading ui file 'functionWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_functionWindow(object):
    def setupUi(self, functionWindow):
        functionWindow.setObjectName("functionWindow")
        functionWindow.resize(800, 600)
        functionWindow.setMinimumSize(QtCore.QSize(800, 600))
        functionWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.sWFuncWindow = QtWidgets.QStackedWidget(parent=functionWindow)
        self.sWFuncWindow.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.sWFuncWindow.setObjectName("sWFuncWindow")
        self.graphViewer = QtWidgets.QWidget()
        self.graphViewer.setObjectName("graphViewer")
        self.frameFuncWindowBar = QtWidgets.QFrame(parent=self.graphViewer)
        self.frameFuncWindowBar.setGeometry(QtCore.QRect(0, 0, 801, 71))
        self.frameFuncWindowBar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameFuncWindowBar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameFuncWindowBar.setObjectName("frameFuncWindowBar")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.frameFuncWindowBar)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 631, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lytfuncWindowBar = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lytfuncWindowBar.setContentsMargins(0, 0, 0, 0)
        self.lytfuncWindowBar.setObjectName("lytfuncWindowBar")
        self.btnFuncSWindowave = QtWidgets.QPushButton(parent=self.frameFuncWindowBar)
        self.btnFuncSWindowave.setGeometry(QtCore.QRect(640, 20, 150, 24))
        self.btnFuncSWindowave.setObjectName("btnFuncSWindowave")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.graphViewer)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 90, 661, 451))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.lytFuncWindowCanvas = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.lytFuncWindowCanvas.setContentsMargins(0, 0, 0, 0)
        self.lytFuncWindowCanvas.setObjectName("lytFuncWindowCanvas")
        self.btnFuncWindowHome = QtWidgets.QPushButton(parent=self.graphViewer)
        self.btnFuncWindowHome.setGeometry(QtCore.QRect(320, 560, 160, 25))
        self.btnFuncWindowHome.setObjectName("btnFuncWindowHome")
        self.sWFuncWindow.addWidget(self.graphViewer)
        self.twoDimGraph = QtWidgets.QWidget()
        self.twoDimGraph.setObjectName("twoDimGraph")
        self.sWFuncWindow.addWidget(self.twoDimGraph)
        self.threeDimGraph = QtWidgets.QWidget()
        self.threeDimGraph.setObjectName("threeDimGraph")
        self.sWFuncWindow.addWidget(self.threeDimGraph)
        self.implicitGraph = QtWidgets.QWidget()
        self.implicitGraph.setObjectName("implicitGraph")
        self.sWFuncWindow.addWidget(self.implicitGraph)

        self.retranslateUi(functionWindow)
        QtCore.QMetaObject.connectSlotsByName(functionWindow)

    def retranslateUi(self, functionWindow):
        _translate = QtCore.QCoreApplication.translate
        functionWindow.setWindowTitle(_translate("functionWindow", "Dialog"))
        self.btnFuncSWindowave.setText(_translate("functionWindow", "Save"))
        self.btnFuncWindowHome.setText(_translate("functionWindow", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    functionWindow = QtWidgets.QDialog()
    ui = Ui_functionWindow()
    ui.setupUi(functionWindow)
    functionWindow.show()
    sys.exit(app.exec())
