# Form implementation generated from reading ui file 'graphTransformation.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_graphTransformation(object):
    def setupUi(self, graphTransformation):
        graphTransformation.setObjectName("graphTransformation")
        graphTransformation.resize(400, 300)
        graphTransformation.setMaximumSize(QtCore.QSize(400, 300))
        self.txtGTXSF = QtWidgets.QLineEdit(parent=graphTransformation)
        self.txtGTXSF.setGeometry(QtCore.QRect(60, 70, 113, 21))
        self.txtGTXSF.setText("")
        self.txtGTXSF.setObjectName("txtGTXSF")
        self.txtGTYSF = QtWidgets.QLineEdit(parent=graphTransformation)
        self.txtGTYSF.setGeometry(QtCore.QRect(220, 70, 113, 21))
        self.txtGTYSF.setObjectName("txtGTYSF")
        self.txtGTYVector = QtWidgets.QLineEdit(parent=graphTransformation)
        self.txtGTYVector.setGeometry(QtCore.QRect(220, 130, 113, 21))
        self.txtGTYVector.setObjectName("txtGTYVector")
        self.txtGTXVector = QtWidgets.QLineEdit(parent=graphTransformation)
        self.txtGTXVector.setGeometry(QtCore.QRect(60, 130, 113, 21))
        self.txtGTXVector.setObjectName("txtGTXVector")
        self.btnGTGraph = QtWidgets.QPushButton(parent=graphTransformation)
        self.btnGTGraph.setGeometry(QtCore.QRect(90, 200, 75, 24))
        self.btnGTGraph.setObjectName("btnGTGraph")
        self.btnGTCancel = QtWidgets.QPushButton(parent=graphTransformation)
        self.btnGTCancel.setGeometry(QtCore.QRect(230, 200, 75, 24))
        self.btnGTCancel.setObjectName("btnGTCancel")

        self.retranslateUi(graphTransformation)
        QtCore.QMetaObject.connectSlotsByName(graphTransformation)

    def retranslateUi(self, graphTransformation):
        _translate = QtCore.QCoreApplication.translate
        graphTransformation.setWindowTitle(_translate("graphTransformation", "Dialog"))
        self.txtGTXSF.setPlaceholderText(_translate("graphTransformation", "X Scale Factor:"))
        self.txtGTYSF.setPlaceholderText(_translate("graphTransformation", "Y Scale Factor:"))
        self.txtGTYVector.setPlaceholderText(_translate("graphTransformation", "Y Translation:"))
        self.txtGTXVector.setPlaceholderText(_translate("graphTransformation", "X Translation:"))
        self.btnGTGraph.setText(_translate("graphTransformation", "Graph"))
        self.btnGTCancel.setText(_translate("graphTransformation", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    graphTransformation = QtWidgets.QDialog()
    ui = Ui_graphTransformation()
    ui.setupUi(graphTransformation)
    graphTransformation.show()
    sys.exit(app.exec())
