# Form implementation generated from reading ui file 'dataWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dataWindow(object):
    def setupUi(self, dataWindow):
        dataWindow.setObjectName("dataWindow")
        dataWindow.resize(800, 600)
        dataWindow.setMinimumSize(QtCore.QSize(800, 600))
        dataWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.sWDataWindow = QtWidgets.QStackedWidget(parent=dataWindow)
        self.sWDataWindow.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.sWDataWindow.setObjectName("sWDataWindow")
        self.dataTable = QtWidgets.QWidget()
        self.dataTable.setObjectName("dataTable")
        self.tblTDataPoints = QtWidgets.QTableWidget(parent=self.dataTable)
        self.tblTDataPoints.setGeometry(QtCore.QRect(50, 30, 700, 460))
        self.tblTDataPoints.setMinimumSize(QtCore.QSize(700, 460))
        self.tblTDataPoints.setMaximumSize(QtCore.QSize(700, 460))
        self.tblTDataPoints.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.tblTDataPoints.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.tblTDataPoints.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.tblTDataPoints.setAutoScroll(False)
        self.tblTDataPoints.setObjectName("tblTDataPoints")
        self.tblTDataPoints.setColumnCount(2)
        self.tblTDataPoints.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tblTDataPoints.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTDataPoints.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTDataPoints.setHorizontalHeaderItem(1, item)
        self.tblTDataPoints.horizontalHeader().setCascadingSectionResizes(False)
        self.tblTDataPoints.horizontalHeader().setDefaultSectionSize(341)
        self.tblTDataPoints.horizontalHeader().setSortIndicatorShown(False)
        self.tblTDataPoints.horizontalHeader().setStretchLastSection(True)
        self.btnTDataCSV = QtWidgets.QPushButton(parent=self.dataTable)
        self.btnTDataCSV.setGeometry(QtCore.QRect(305, 500, 191, 24))
        self.btnTDataCSV.setObjectName("btnTDataCSV")
        self.btnTDataRow = QtWidgets.QPushButton(parent=self.dataTable)
        self.btnTDataRow.setGeometry(QtCore.QRect(305, 540, 191, 24))
        self.btnTDataRow.setObjectName("btnTDataRow")
        self.btnTDataGraph = QtWidgets.QPushButton(parent=self.dataTable)
        self.btnTDataGraph.setGeometry(QtCore.QRect(90, 540, 191, 24))
        self.btnTDataGraph.setObjectName("btnTDataGraph")
        self.btnTDataHome = QtWidgets.QPushButton(parent=self.dataTable)
        self.btnTDataHome.setGeometry(QtCore.QRect(520, 540, 191, 24))
        self.btnTDataHome.setObjectName("btnTDataHome")
        self.sWDataWindow.addWidget(self.dataTable)
        self.graphViewer = QtWidgets.QWidget()
        self.graphViewer.setObjectName("graphViewer")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.graphViewer)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(80, 90, 661, 451))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.lytDataWindowCanvas = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.lytDataWindowCanvas.setContentsMargins(0, 0, 0, 0)
        self.lytDataWindowCanvas.setObjectName("lytDataWindowCanvas")
        self.frameDataWindowBar = QtWidgets.QFrame(parent=self.graphViewer)
        self.frameDataWindowBar.setGeometry(QtCore.QRect(0, 0, 801, 71))
        self.frameDataWindowBar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameDataWindowBar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameDataWindowBar.setObjectName("frameDataWindowBar")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.frameDataWindowBar)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lytDataWindowBar = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lytDataWindowBar.setContentsMargins(0, 0, 0, 0)
        self.lytDataWindowBar.setObjectName("lytDataWindowBar")
        self.btnDataWindowHome = QtWidgets.QPushButton(parent=self.graphViewer)
        self.btnDataWindowHome.setGeometry(QtCore.QRect(330, 560, 161, 24))
        self.btnDataWindowHome.setObjectName("btnDataWindowHome")
        self.sWDataWindow.addWidget(self.graphViewer)

        self.retranslateUi(dataWindow)
        self.sWDataWindow.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dataWindow)

    def retranslateUi(self, dataWindow):
        _translate = QtCore.QCoreApplication.translate
        dataWindow.setWindowTitle(_translate("dataWindow", "Dialog"))
        self.tblTDataPoints.setSortingEnabled(False)
        item = self.tblTDataPoints.verticalHeaderItem(0)
        item.setText(_translate("dataWindow", "1"))
        item = self.tblTDataPoints.horizontalHeaderItem(0)
        item.setText(_translate("dataWindow", "X"))
        item = self.tblTDataPoints.horizontalHeaderItem(1)
        item.setText(_translate("dataWindow", "Y"))
        self.btnTDataCSV.setText(_translate("dataWindow", "Import CSV"))
        self.btnTDataRow.setText(_translate("dataWindow", "Add Row"))
        self.btnTDataGraph.setText(_translate("dataWindow", "Graph"))
        self.btnTDataHome.setText(_translate("dataWindow", "Home"))
        self.btnDataWindowHome.setText(_translate("dataWindow", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dataWindow = QtWidgets.QDialog()
    ui = Ui_dataWindow()
    ui.setupUi(dataWindow)
    dataWindow.show()
    sys.exit(app.exec())
