# Form implementation generated from reading ui file 'dataWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dataWindow(object):
    def setupUi(self, dataWindow):
        dataWindow.setObjectName("dataWindow")
        dataWindow.resize(800, 600)
        dataWindow.setMinimumSize(QtCore.QSize(800, 600))
        dataWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.btnDataWindowHome = QtWidgets.QPushButton(parent=dataWindow)
        self.btnDataWindowHome.setGeometry(QtCore.QRect(320, 560, 161, 24))
        self.btnDataWindowHome.setObjectName("btnDataWindowHome")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=dataWindow)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(69, 89, 661, 451))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.lytDataWindowCanvas = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.lytDataWindowCanvas.setContentsMargins(0, 0, 0, 0)
        self.lytDataWindowCanvas.setObjectName("lytDataWindowCanvas")
        self.frameDataWindowBar = QtWidgets.QFrame(parent=dataWindow)
        self.frameDataWindowBar.setGeometry(QtCore.QRect(0, 0, 801, 71))
        self.frameDataWindowBar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameDataWindowBar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameDataWindowBar.setObjectName("frameDataWindowBar")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.frameDataWindowBar)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.lytDataWindowBar = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.lytDataWindowBar.setContentsMargins(0, 0, 0, 0)
        self.lytDataWindowBar.setObjectName("lytDataWindowBar")

        self.retranslateUi(dataWindow)
        QtCore.QMetaObject.connectSlotsByName(dataWindow)

    def retranslateUi(self, dataWindow):
        _translate = QtCore.QCoreApplication.translate
        dataWindow.setWindowTitle(_translate("dataWindow", "Dialog"))
        self.btnDataWindowHome.setText(_translate("dataWindow", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dataWindow = QtWidgets.QDialog()
    ui = Ui_dataWindow()
    ui.setupUi(dataWindow)
    dataWindow.show()
    sys.exit(app.exec())
