# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_loginWindow(object):
    def setupUi(self, loginWindow):
        loginWindow.setObjectName("loginWindow")
        loginWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=loginWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.lblLogin = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblLogin.setGeometry(QtCore.QRect(270, 50, 251, 171))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lblLogin.setFont(font)
        self.lblLogin.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblLogin.setObjectName("lblLogin")
        self.txtLoginUname = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtLoginUname.setGeometry(QtCore.QRect(280, 210, 231, 31))
        self.txtLoginUname.setObjectName("txtLoginUname")
        self.txtLoginPWord = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtLoginPWord.setGeometry(QtCore.QRect(280, 280, 231, 31))
        self.txtLoginPWord.setStyleSheet("")
        self.txtLoginPWord.setText("")
        self.txtLoginPWord.setObjectName("txtLoginPWord")
        self.btnLoginPVis = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLoginPVis.setGeometry(QtCore.QRect(473, 284, 32, 32))
        self.btnLoginPVis.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border-color: rgba(255, 255, 255, 0);\n"
"}")
        self.btnLoginPVis.setText("")
        self.btnLoginPVis.setCheckable(True)
        self.btnLoginPVis.setObjectName("btnLoginPVis")
        self.gVLogin = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.gVLogin.setGeometry(QtCore.QRect(170, 20, 450, 550))
        self.gVLogin.setMinimumSize(QtCore.QSize(450, 550))
        self.gVLogin.setMaximumSize(QtCore.QSize(450, 550))
        self.gVLogin.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.gVLogin.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.gVLogin.setObjectName("gVLogin")
        self.btnFPword = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnFPword.setGeometry(QtCore.QRect(340, 330, 111, 24))
        self.btnFPword.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.btnFPword.setObjectName("btnFPword")
        self.btnLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLogin.setGeometry(QtCore.QRect(310, 370, 161, 24))
        self.btnLogin.setObjectName("btnLogin")
        self.btnLoginCancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLoginCancel.setGeometry(QtCore.QRect(310, 420, 161, 24))
        self.btnLoginCancel.setObjectName("btnLoginCancel")
        self.btnLoginRegister = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLoginRegister.setGeometry(QtCore.QRect(310, 470, 161, 24))
        self.btnLoginRegister.setObjectName("btnLoginRegister")
        self.gVLogin.raise_()
        self.txtLoginUname.raise_()
        self.txtLoginPWord.raise_()
        self.lblLogin.raise_()
        self.btnLoginPVis.raise_()
        self.btnFPword.raise_()
        self.btnLogin.raise_()
        self.btnLoginCancel.raise_()
        self.btnLoginRegister.raise_()
        loginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(loginWindow)
        QtCore.QMetaObject.connectSlotsByName(loginWindow)

    def retranslateUi(self, loginWindow):
        _translate = QtCore.QCoreApplication.translate
        loginWindow.setWindowTitle(_translate("loginWindow", "MainWindow"))
        self.lblLogin.setText(_translate("loginWindow", "Login"))
        self.txtLoginUname.setPlaceholderText(_translate("loginWindow", "Enter Username:"))
        self.txtLoginPWord.setPlaceholderText(_translate("loginWindow", "Enter Password:"))
        self.btnFPword.setText(_translate("loginWindow", "Forgot Password?"))
        self.btnLogin.setText(_translate("loginWindow", "Login"))
        self.btnLoginCancel.setText(_translate("loginWindow", "Cancel"))
        self.btnLoginRegister.setText(_translate("loginWindow", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginWindow = QtWidgets.QMainWindow()
    ui = Ui_loginWindow()
    ui.setupUi(loginWindow)
    loginWindow.show()
    sys.exit(app.exec())
